name: Build and Release

on:
  workflow_dispatch:
    inputs:
      custom_tag:
        description: "Optional release tag."
        required: false
        default: ""

permissions:
  contents: write

jobs:
  build:
    if: github.event.inputs.custom_tag != ''
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      - uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: "17"

      - name: Create tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          custom_tag: ${{ github.event.inputs.custom_tag }}
          release_branches: main
          create_annotated_tag: true

      - name: Build Android APKs
        if: steps.tag_version.outputs.new_tag != ''
        run: |
          flutter pub get
          flutter build apk --release --split-per-abi
          ls -l build/app/outputs/flutter-apk/

      - name: Upload Release APKs
        if: steps.tag_version.outputs.new_tag != ''
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.tag_version.outputs.new_tag }}
          name: Release ${{ steps.tag_version.outputs.new_tag }}
          artifacts: "build/app/outputs/flutter-apk/app-arm64-v8a-release.apk,build/app/outputs/flutter-apk/app-armeabi-v7a-release.apk,build/app/outputs/flutter-apk/app-x86_64-release.apk"
          body: ${{ steps.tag_version.outputs.changelog }}
          token: ${{ secrets.GITHUB_TOKEN }}
