name: Build and Release

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          channel: stable
      - run: flutter --version

      - uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: "17"

      - name: Flutter Doctor
        run: flutter doctor -v

      - name: Create tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.SECRET_TOKEN }}

      - name: Build Android APKs
        run: |
          flutter pub get
          flutter build apk --release --split-per-abi
          ls -l build/app/outputs/flutter-apk/

      - name: Upload Release APKs
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.tag_version.outputs.new_tag }}
          name: Release ${{ steps.tag_version.outputs.new_tag }}
          artifacts: "build/app/outputs/flutter-apk/"
          body: ${{ steps.tag_version.outputs.changelog }}
